services:
  ## entrypoint: /usr/bin/entrypoint.sh, para rodar alguma verificação antes de iniciar o serviço
  datalake:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    volumes:
      - minio_data:/data
    networks:
      - datalakehouse
    environment:
      # MINIO_ACCESS_KEY_FILE=access_key 
      # MINIO_SECRET_KEY_FILE=secret_key 
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} 
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} 
      # MINIO_KMS_SECRET_KEY_FILE=kms_master_key 
      # MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav 
      # MINIO_CONFIG_ENV_FILE=config.env MC_
      # CONFIG_DIR=/tmp/.mc
    command: minio server /data --console-address ":9001"
    deploy:
      # replicas: 0
      # resources:
      #   limits:
      #     cpus: '1'
      #     memory: 1G
      #     # pids: 100
      #   reservations:
      #     cpus: '0.1'
      #     memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
      - "9001:9001"


  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metastore_db
    ports:
      - "5432:5432"
    networks:
      - datalakehouse

  hive-server:
    image: hive-with-pgdriver
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      SERVICE_NAME: hiveserver2
      IS_RESUME: "true"
      DB_SERVICE_OPTS: "-Dhive.metastore.uris=thrift://metastore:9083"
    volumes:
      - warehouse:/opt/hive/data/warehouse
    networks:
      - datalakehouse

  hive-metastore:
    image: hive-with-pgdriver
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      DB_SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver 
                        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db 
                        -Djavax.jdo.option.ConnectionUserName=hive 
                        -Djavax.jdo.option.ConnectionPassword=password"
      HIVE_CUSTOM_CONF_DIR: "./hive_custom_conf"
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive_custom_conf/:/opt/hive/conf
    networks:
      - datalakehouse


networks:
  datalakehouse:
    driver: bridge

volumes:
  minio_data:
  warehouse: