services:
  spark-master:
    image: bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8282:8080"
    networks:
      - datalakehouse

  spark-worker:
    image: bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
    depends_on:
      - spark-master
    networks:
      - datalakehouse

  jupyter-spark:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ENDPOINT=datalake:9000
      - SPARK_MASTER_URL=spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
      - XDG_DATA_HOME=/tmp/.local/share
      - XDG_CONFIG_HOME=/tmp/.config
      - XDG_CACHE_HOME=/tmp/.cache
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./config:/config
    working_dir: /notebooks
    depends_on:
      spark-master:
        condition: service_started
      spark-worker:
        condition: service_started
    networks:
      - datalakehouse

networks:
  data_management:
    external: true
  datalakehouse:
    external: true
