version: "3.8"

services:
  spark-master:
    image: bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - datalakehouse

  spark-worker:
    image: bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
    depends_on:
      - spark-master
    networks:
      - datalakehouse

  jupyter-spark:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ENDPOINT=datalake:9000
      - SPARK_MASTER_URL=spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ../../scripts:/home/jovyan/scripts
    depends_on:
      spark-master:
        condition: service_started
      spark-worker:
        condition: service_started
      datalake:
        condition: service_started
    networks:
      - datalakehouse

networks:
  datalakehouse:
    external: true
